package cornet_desktop;

import cornet_desktop.Model.MTModel;
import cornet_desktop.presenter.AHSPresenter;
import cornet_desktop.utils.Utils;

import java.util.List;

public class AHS extends javax.swing.JFrame {
    private final AHSPresenter hsp = new AHSPresenter();
    private final Utils utils = new Utils();
    
    public AHS() {
        initComponents();
        hsp.loadDatanamaPT();
        hsp.loadDatanamaMT();
        hsp.loadDataclassPT();
        hsp.loadTipePondasi();
        hsp.loadClassPondasi();
        this.loadPT();
        this.loadclassPT();
        
    }
    
    private void loadclassPT(){
        List<String>
         clList = hsp.getClassPT();
        for(String data
                : clList){
            DCPondasi.addItem(data);
        }
    }
    
   private void loadPT(){
        List<String>
         ptList = hsp.getNamaPT();
        for(String data
                : ptList){
            DTT.addItem(data);
        }
    }

     private void loadMT(){
        List<String> mtList = hsp.getNamaMT();
        for(String data
                : mtList){
            DBasisMT.addItem(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        QuanKMR = new javax.swing.JLabel();
        SatuanKMR = new javax.swing.JLabel();
        HargaKMR = new javax.swing.JLabel();
        KMR = new javax.swing.JLabel();
        Pondasi = new javax.swing.JLabel();
        AHS = new javax.swing.JLabel();
        CPondasi = new javax.swing.JLabel();
        HPondasi = new javax.swing.JLabel();
        TT = new javax.swing.JLabel();
        Erect = new javax.swing.JLabel();
        BeratErect = new javax.swing.JLabel();
        HargaErect = new javax.swing.JLabel();
        MT = new javax.swing.JLabel();
        BasisMT = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        HargaMT = new javax.swing.JLabel();
        DCPondasi = new javax.swing.JComboBox<>();
        DTT = new javax.swing.JComboBox<>();
        DBasisMT = new javax.swing.JComboBox<>();
        THargaKMR = new javax.swing.JTextField();
        THargaP = new javax.swing.JTextField();
        THargaMT = new javax.swing.JTextField();
        TBeratErect = new javax.swing.JTextField();
        THargaErect = new javax.swing.JTextField();
        dropQuan = new javax.swing.JComboBox<>();
        dropSat = new javax.swing.JComboBox<>();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setMinimumSize(new java.awt.Dimension(1230, 820));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1230, 820));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1230, 820));

        QuanKMR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        QuanKMR.setForeground(new java.awt.Color(240, 240, 240));
        QuanKMR.setText("Quantity");

        SatuanKMR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        SatuanKMR.setForeground(new java.awt.Color(240, 240, 240));
        SatuanKMR.setText("Satuan");

        HargaKMR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        HargaKMR.setForeground(new java.awt.Color(255, 255, 255));
        HargaKMR.setText("Harga");

        KMR.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        KMR.setForeground(new java.awt.Color(255, 255, 255));
        KMR.setText("Pekerjaan Persiapan");

        Pondasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Pondasi.setForeground(new java.awt.Color(240, 240, 240));
        Pondasi.setText("Pondasi");

        AHS.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        AHS.setForeground(new java.awt.Color(255, 255, 255));
        AHS.setText("AHS PEKERJAAN SIPIL");

        CPondasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        CPondasi.setForeground(new java.awt.Color(240, 240, 240));
        CPondasi.setText("Class Pondasi");

        HPondasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        HPondasi.setForeground(new java.awt.Color(240, 240, 240));
        HPondasi.setText("Harga");

        TT.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        TT.setForeground(new java.awt.Color(240, 240, 240));
        TT.setText("Tipe Tower");

        Erect.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Erect.setForeground(new java.awt.Color(240, 240, 240));
        Erect.setText("Erection");

        BeratErect.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BeratErect.setForeground(new java.awt.Color(240, 240, 240));
        BeratErect.setText("Berat");

        HargaErect.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        HargaErect.setForeground(new java.awt.Color(240, 240, 240));
        HargaErect.setText("Harga");

        MT.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        MT.setForeground(new java.awt.Color(240, 240, 240));
        MT.setText("Material Tower");

        BasisMT.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        BasisMT.setForeground(new java.awt.Color(240, 240, 240));
        BasisMT.setText("Basis");

        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo/logo PLN fix.png"))); // NOI18N
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });

        HargaMT.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        HargaMT.setForeground(new java.awt.Color(240, 240, 240));
        HargaMT.setText("Harga");

        DCPondasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DCPondasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        DCPondasi.setMinimumSize(new java.awt.Dimension(200, 30));
        DCPondasi.setPreferredSize(new java.awt.Dimension(200, 30));
        DCPondasi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DCPondasiItemStateChanged(evt);
            }
        });
        DCPondasi.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DCPondasiInputMethodTextChanged(evt);
            }
        });
        DCPondasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCPondasiActionPerformed(evt);
            }
        });

        DTT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        DTT.setMinimumSize(new java.awt.Dimension(200, 30));
        DTT.setPreferredSize(new java.awt.Dimension(200, 30));
        DTT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DTTItemStateChanged(evt);
            }
        });
        DTT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DTTInputMethodTextChanged(evt);
            }
        });
        DTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTTActionPerformed(evt);
            }
        });

        DBasisMT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DBasisMT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        DBasisMT.setMinimumSize(new java.awt.Dimension(200, 30));
        DBasisMT.setPreferredSize(new java.awt.Dimension(200, 30));
        DBasisMT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DBasisMTItemStateChanged(evt);
            }
        });

        THargaKMR.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        THargaKMR.setMinimumSize(new java.awt.Dimension(250, 30));
        THargaKMR.setPreferredSize(new java.awt.Dimension(250, 30));
        THargaKMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaKMRActionPerformed(evt);
            }
        });

        THargaP.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        THargaP.setMinimumSize(new java.awt.Dimension(250, 30));
        THargaP.setPreferredSize(new java.awt.Dimension(250, 30));
        THargaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaPActionPerformed(evt);
            }
        });

        THargaMT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        THargaMT.setMinimumSize(new java.awt.Dimension(250, 30));
        THargaMT.setPreferredSize(new java.awt.Dimension(250, 30));
        THargaMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaMTActionPerformed(evt);
            }
        });

        TBeratErect.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TBeratErect.setMinimumSize(new java.awt.Dimension(200, 30));
        TBeratErect.setPreferredSize(new java.awt.Dimension(200, 30));
        TBeratErect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBeratErectActionPerformed(evt);
            }
        });

        THargaErect.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        THargaErect.setMinimumSize(new java.awt.Dimension(250, 30));
        THargaErect.setPreferredSize(new java.awt.Dimension(250, 30));
        THargaErect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THargaErectActionPerformed(evt);
            }
        });

        dropQuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        dropQuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih-", "1" }));
        dropQuan.setMinimumSize(new java.awt.Dimension(200, 30));
        dropQuan.setPreferredSize(new java.awt.Dimension(200, 30));

        dropSat.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        dropSat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih-", "KMR" }));
        dropSat.setMinimumSize(new java.awt.Dimension(200, 30));
        dropSat.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo)
                .addGap(327, 327, 327)
                .addComponent(AHS)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KMR)
                    .addComponent(TT)
                    .addComponent(DTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MT)
                            .addComponent(Erect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BasisMT)
                            .addComponent(DBasisMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BeratErect)
                            .addComponent(TBeratErect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pondasi)
                            .addComponent(QuanKMR)
                            .addComponent(dropQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SatuanKMR)
                                .addComponent(dropSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DCPondasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPondasi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(THargaMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(THargaErect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaMT)
                    .addComponent(HargaErect)
                    .addComponent(HPondasi)
                    .addComponent(THargaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HargaKMR)
                    .addComponent(THargaKMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AHS)
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(QuanKMR)
                                    .addComponent(KMR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dropQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SatuanKMR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dropSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HargaKMR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(THargaKMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(HPondasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(THargaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CPondasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(DCPondasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Pondasi))))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(HargaMT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(THargaMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(HargaErect)
                                .addGap(18, 18, 18)
                                .addComponent(THargaErect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BasisMT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DBasisMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BeratErect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TBeratErect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(TT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(MT)
                        .addGap(122, 122, 122)
                        .addComponent(Erect)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1230, 820);

        Background.setBackground(new java.awt.Color(0, 0, 51));
        Background.setForeground(new java.awt.Color(0, 0, 51));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/bg_content1.jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(850, 550));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1230, 820);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void THargaKMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaKMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaKMRActionPerformed

    private void THargaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaPActionPerformed

    private void DTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DTTActionPerformed

    private void TBeratErectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBeratErectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBeratErectActionPerformed

    private void THargaErectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaErectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaErectActionPerformed

    private void DCPondasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCPondasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCPondasiActionPerformed

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        new home().setVisible(true); 
        this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_LogoMouseClicked

    private void DTTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DTTInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DTTInputMethodTextChanged

    private void DTTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DTTItemStateChanged
        String tipeTower = DTT.getSelectedItem().toString();
        if(tipeTower != "- pilih -"){
            //load data basis berdasarkan tipe
            hsp.loadBasisMaterial(tipeTower);
            DBasisMT.removeAllItems();
            DBasisMT.addItem("- pilih -");
            List<String> basisMaterial = hsp.getNamaMT();
            for(String basis : basisMaterial){
                DBasisMT.addItem(basis);
            }
            dropQuan.setSelectedIndex(1);
            dropSat.setSelectedIndex(1);
            Utils ut = new Utils();
            String currentcy = String.valueOf("461689150.909928");
            THargaKMR.setText(ut.getCurrencyFormat(currentcy));
            DBasisMT.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_DTTItemStateChanged

    private void DCPondasiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DCPondasiItemStateChanged
        String tipeTower = DTT.getSelectedItem().toString();
        String classPondasi = DCPondasi.getSelectedItem().toString();
        if(tipeTower != "- pilih -" && classPondasi != "- pilih -"){
            String harga = hsp.getHargaPondasi(tipeTower, classPondasi);
            THargaP.setText(utils.getCurrencyFormat(harga));
        }
    }//GEN-LAST:event_DCPondasiItemStateChanged

    private void DCPondasiInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DCPondasiInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DCPondasiInputMethodTextChanged

    private void DBasisMTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DBasisMTItemStateChanged
        int size = DBasisMT.getItemCount();
        if(size > 0){
            String tipeTower = DTT.getSelectedItem().toString();
            String basisTower = DBasisMT.getSelectedItem().toString();
            if(tipeTower != "- pilih -" && basisTower != "- pilih -"){
                System.out.println(basisTower);
                MTModel material = hsp.getMaterialTower(tipeTower, basisTower);
                TBeratErect.setText(material.getBerat()+" KG");
                double hargaPermenperin = Double.parseDouble(material.getHarga_permenperin());
                THargaMT.setText(utils.getCurrencyFormat(String.valueOf(hargaPermenperin)));
                THargaErect.setText(utils.getCurrencyFormat(material.getHarga_erection()));
            }
        }
    }//GEN-LAST:event_DBasisMTItemStateChanged

    private void THargaMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THargaMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THargaMTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AHS;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BasisMT;
    private javax.swing.JLabel BeratErect;
    private javax.swing.JLabel CPondasi;
    private javax.swing.JComboBox<String> DBasisMT;
    private javax.swing.JComboBox<String> DCPondasi;
    private javax.swing.JComboBox<String> DTT;
    private javax.swing.JLabel Erect;
    private javax.swing.JLabel HPondasi;
    private javax.swing.JLabel HargaErect;
    private javax.swing.JLabel HargaKMR;
    private javax.swing.JLabel HargaMT;
    private javax.swing.JLabel KMR;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MT;
    private javax.swing.JLabel Pondasi;
    private javax.swing.JLabel QuanKMR;
    private javax.swing.JLabel SatuanKMR;
    private javax.swing.JTextField TBeratErect;
    private javax.swing.JTextField THargaErect;
    private javax.swing.JTextField THargaKMR;
    private javax.swing.JTextField THargaMT;
    private javax.swing.JTextField THargaP;
    private javax.swing.JLabel TT;
    private javax.swing.JComboBox<String> dropQuan;
    private javax.swing.JComboBox<String> dropSat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
