/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cornet_desktop;
import cornet_desktop.database.DBConnection;
import cornet_desktop.presenter.EMPresenter;
import cornet_desktop.utils.Utils;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Universal
 */
public class AHSEM extends javax.swing.JFrame {
 private final EMPresenter emp = new EMPresenter();
    /**
     * Creates new form AHSEM
     */
    public AHSEM() {
        initComponents(); 
        emp.loadDataStringing();
        emp.loadDataInsulator();
        emp.loadDataAksesoris();
        this.loadStringing();
        this.loadInsulator();
        this.loadAksesoris();
//        this.loadSatuanStringing();
    }
    
    private void loadStringing(){
        List<String>
           stList= emp.getNamaStringing();
        for(String data: stList){
            stringing_combo_box.addItem(data);
        }
//        List<String>
//           satstList= emp.getSatuanStringing();
//        for(String satuan: satstList){
//            satuan_stringing_combo_box.addItem(satuan);
//        }
    }
    
//    private void loadSatuanSteinging(){
//        List<String>
//           hst= emp.getHargaStringing();
//        for(String data: hst){
//            text_harga_stringing.setText(data);
//        }
//    }
    
    private void loadInsulator(){
        List<String>
           inList= emp.getNamaInsulator();
        for(String data: inList){
            insulator_combo_box.addItem(data);
        }
    }
    
     private void loadAksesoris(){
        List<String>
           akList= emp.getNamaAksesoris();
        for(String data: akList){
            nama_aksesoris_box.addItem(data);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelAHSEM = new javax.swing.JPanel();
        logo_pln = new javax.swing.JLabel();
        stringing_combo_box = new javax.swing.JComboBox<>();
        insulator_combo_box = new javax.swing.JComboBox<>();
        nama_aksesoris_box = new javax.swing.JComboBox<>();
        stringing_quantity_combo_box = new javax.swing.JComboBox<>();
        aksesoris_quantity_combo_box = new javax.swing.JComboBox<>();
        insulator_quantity_combo_box = new javax.swing.JComboBox<>();
        jText_harga = new javax.swing.JTextField();
        text_harga_insulator = new javax.swing.JTextField();
        text_harga_aksesoris = new javax.swing.JTextField();
        text_harga_stringing = new javax.swing.JTextField();
        jText_komisioning_jumlah_tower = new javax.swing.JTextField();
        text_judul_AHS_pekerjaan_EM = new javax.swing.JLabel();
        insulator_tabel = new javax.swing.JLabel();
        Stringing_label = new javax.swing.JLabel();
        komisioning_jumlah_tower_label = new javax.swing.JLabel();
        Aksesoris_label = new javax.swing.JLabel();
        harga_stringing_label = new javax.swing.JLabel();
        harga_insulator_label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        harga_aksesoris_label = new javax.swing.JLabel();
        quantity_insulator_label = new javax.swing.JLabel();
        quantity_stringing_label = new javax.swing.JLabel();
        quantity_aksesoris_label = new javax.swing.JLabel();
        satuan_stringing_label = new javax.swing.JLabel();
        satuan_insulator_label = new javax.swing.JLabel();
        satuan_aksesoris_label = new javax.swing.JLabel();
        satuan_aksesoris_TextField = new javax.swing.JTextField();
        satuan_stringing = new javax.swing.JTextField();
        satuan_insulator = new javax.swing.JTextField();
        background_content = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stringing");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Komisioning Jumlah Tower");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Quantity");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Satuan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1230, 820));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanelAHSEM.setBackground(new java.awt.Color(0, 24, 72));
        jPanelAHSEM.setOpaque(false);
        jPanelAHSEM.setPreferredSize(new java.awt.Dimension(1230, 820));

        logo_pln.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo/logo PLN fix.png"))); // NOI18N
        logo_pln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_plnMouseClicked(evt);
            }
        });

        stringing_combo_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        stringing_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        stringing_combo_box.setMinimumSize(new java.awt.Dimension(300, 30));
        stringing_combo_box.setPreferredSize(new java.awt.Dimension(300, 30));
        stringing_combo_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stringing_combo_boxItemStateChanged(evt);
            }
        });
        stringing_combo_box.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                stringing_combo_boxInputMethodTextChanged(evt);
            }
        });
        stringing_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringing_combo_boxActionPerformed(evt);
            }
        });

        insulator_combo_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        insulator_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        insulator_combo_box.setMinimumSize(new java.awt.Dimension(300, 30));
        insulator_combo_box.setPreferredSize(new java.awt.Dimension(300, 30));
        insulator_combo_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                insulator_combo_boxItemStateChanged(evt);
            }
        });
        insulator_combo_box.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                insulator_combo_boxInputMethodTextChanged(evt);
            }
        });
        insulator_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insulator_combo_boxActionPerformed(evt);
            }
        });

        nama_aksesoris_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        nama_aksesoris_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -" }));
        nama_aksesoris_box.setMinimumSize(new java.awt.Dimension(300, 30));
        nama_aksesoris_box.setPreferredSize(new java.awt.Dimension(300, 30));
        nama_aksesoris_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nama_aksesoris_boxItemStateChanged(evt);
            }
        });
        nama_aksesoris_box.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nama_aksesoris_boxInputMethodTextChanged(evt);
            }
        });

        stringing_quantity_combo_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        stringing_quantity_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-pilih-", "1" }));
        stringing_quantity_combo_box.setMinimumSize(new java.awt.Dimension(200, 30));
        stringing_quantity_combo_box.setPreferredSize(new java.awt.Dimension(200, 30));
        stringing_quantity_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stringing_quantity_combo_boxActionPerformed(evt);
            }
        });

        aksesoris_quantity_combo_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        aksesoris_quantity_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -", "1" }));
        aksesoris_quantity_combo_box.setMinimumSize(new java.awt.Dimension(200, 30));
        aksesoris_quantity_combo_box.setPreferredSize(new java.awt.Dimension(200, 30));
        aksesoris_quantity_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aksesoris_quantity_combo_boxActionPerformed(evt);
            }
        });

        insulator_quantity_combo_box.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        insulator_quantity_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- pilih -", "1" }));
        insulator_quantity_combo_box.setMinimumSize(new java.awt.Dimension(200, 30));
        insulator_quantity_combo_box.setPreferredSize(new java.awt.Dimension(200, 30));
        insulator_quantity_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insulator_quantity_combo_boxActionPerformed(evt);
            }
        });

        jText_harga.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jText_harga.setMinimumSize(new java.awt.Dimension(250, 30));
        jText_harga.setPreferredSize(new java.awt.Dimension(250, 30));
        jText_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_hargaActionPerformed(evt);
            }
        });

        text_harga_insulator.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        text_harga_insulator.setMinimumSize(new java.awt.Dimension(250, 30));
        text_harga_insulator.setPreferredSize(new java.awt.Dimension(250, 30));
        text_harga_insulator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_harga_insulatorActionPerformed(evt);
            }
        });

        text_harga_aksesoris.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        text_harga_aksesoris.setMinimumSize(new java.awt.Dimension(250, 30));
        text_harga_aksesoris.setPreferredSize(new java.awt.Dimension(250, 30));
        text_harga_aksesoris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_harga_aksesorisActionPerformed(evt);
            }
        });

        text_harga_stringing.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        text_harga_stringing.setMinimumSize(new java.awt.Dimension(250, 30));
        text_harga_stringing.setPreferredSize(new java.awt.Dimension(250, 30));
        text_harga_stringing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_harga_stringingActionPerformed(evt);
            }
        });

        jText_komisioning_jumlah_tower.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jText_komisioning_jumlah_tower.setMinimumSize(new java.awt.Dimension(200, 30));
        jText_komisioning_jumlah_tower.setPreferredSize(new java.awt.Dimension(200, 30));
        jText_komisioning_jumlah_tower.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jText_komisioning_jumlah_towerCaretUpdate(evt);
            }
        });

        text_judul_AHS_pekerjaan_EM.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        text_judul_AHS_pekerjaan_EM.setForeground(new java.awt.Color(255, 255, 255));
        text_judul_AHS_pekerjaan_EM.setText("AHS  PEKERJAAN E/M ");

        insulator_tabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        insulator_tabel.setForeground(new java.awt.Color(255, 255, 255));
        insulator_tabel.setText("Insulator");

        Stringing_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Stringing_label.setForeground(new java.awt.Color(255, 255, 255));
        Stringing_label.setText("Stringing");

        komisioning_jumlah_tower_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        komisioning_jumlah_tower_label.setForeground(new java.awt.Color(255, 255, 255));
        komisioning_jumlah_tower_label.setText("Komisioning Jumlah Tower");

        Aksesoris_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Aksesoris_label.setForeground(new java.awt.Color(255, 255, 255));
        Aksesoris_label.setText("Aksesoris");

        harga_stringing_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        harga_stringing_label.setForeground(new java.awt.Color(255, 255, 255));
        harga_stringing_label.setText("Harga");

        harga_insulator_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        harga_insulator_label.setForeground(new java.awt.Color(255, 255, 255));
        harga_insulator_label.setText("Harga");

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Harga");

        harga_aksesoris_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        harga_aksesoris_label.setForeground(new java.awt.Color(255, 255, 255));
        harga_aksesoris_label.setText("Harga");

        quantity_insulator_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        quantity_insulator_label.setForeground(new java.awt.Color(255, 255, 255));
        quantity_insulator_label.setText("Quantity");

        quantity_stringing_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        quantity_stringing_label.setForeground(new java.awt.Color(255, 255, 255));
        quantity_stringing_label.setText("Quantity");

        quantity_aksesoris_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        quantity_aksesoris_label.setForeground(new java.awt.Color(255, 255, 255));
        quantity_aksesoris_label.setText("Quantity");

        satuan_stringing_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        satuan_stringing_label.setForeground(new java.awt.Color(255, 255, 255));
        satuan_stringing_label.setText("Satuan");

        satuan_insulator_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        satuan_insulator_label.setForeground(new java.awt.Color(255, 255, 255));
        satuan_insulator_label.setText("Satuan");

        satuan_aksesoris_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        satuan_aksesoris_label.setForeground(new java.awt.Color(255, 255, 255));
        satuan_aksesoris_label.setText("Satuan");

        satuan_aksesoris_TextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        satuan_aksesoris_TextField.setMinimumSize(new java.awt.Dimension(200, 30));
        satuan_aksesoris_TextField.setPreferredSize(new java.awt.Dimension(200, 30));

        satuan_stringing.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        satuan_stringing.setMinimumSize(new java.awt.Dimension(200, 30));
        satuan_stringing.setPreferredSize(new java.awt.Dimension(200, 30));
        satuan_stringing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan_stringingActionPerformed(evt);
            }
        });

        satuan_insulator.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        satuan_insulator.setMinimumSize(new java.awt.Dimension(200, 30));
        satuan_insulator.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelAHSEMLayout = new javax.swing.GroupLayout(jPanelAHSEM);
        jPanelAHSEM.setLayout(jPanelAHSEMLayout);
        jPanelAHSEMLayout.setHorizontalGroup(
            jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nama_aksesoris_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stringing_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insulator_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Stringing_label)
                            .addComponent(Aksesoris_label)
                            .addComponent(insulator_tabel)
                            .addComponent(logo_pln))
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(text_judul_AHS_pekerjaan_EM, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stringing_quantity_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(insulator_quantity_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(aksesoris_quantity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(quantity_insulator_label)
                                    .addComponent(quantity_aksesoris_label)
                                    .addComponent(quantity_stringing_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(satuan_aksesoris_label)
                                    .addComponent(satuan_insulator_label)
                                    .addComponent(satuan_aksesoris_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(satuan_stringing_label)
                                    .addComponent(satuan_stringing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(satuan_insulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text_harga_aksesoris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(harga_insulator_label)
                                        .addComponent(harga_stringing_label)
                                        .addComponent(text_harga_stringing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(text_harga_insulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(harga_aksesoris_label))
                                .addGap(25, 25, 25))))
                    .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_komisioning_jumlah_tower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(komisioning_jumlah_tower_label))
                        .addGap(56, 56, 56)
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelAHSEMLayout.setVerticalGroup(
            jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(logo_pln, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(text_judul_AHS_pekerjaan_EM, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(Stringing_label)
                                .addGap(18, 18, 18)
                                .addComponent(stringing_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(insulator_tabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insulator_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(Aksesoris_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_aksesoris_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(quantity_stringing_label)
                                .addGap(18, 18, 18)
                                .addComponent(stringing_quantity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(quantity_insulator_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insulator_quantity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(quantity_aksesoris_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aksesoris_quantity_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAHSEMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(harga_stringing_label)
                                .addGap(18, 18, 18)
                                .addComponent(text_harga_stringing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(satuan_stringing_label)
                                .addGap(18, 18, 18)
                                .addComponent(satuan_stringing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(harga_insulator_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_harga_insulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(harga_aksesoris_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_harga_aksesoris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAHSEMLayout.createSequentialGroup()
                                .addComponent(satuan_insulator_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(satuan_insulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(satuan_aksesoris_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAHSEMLayout.createSequentialGroup()
                                        .addComponent(satuan_aksesoris_label)
                                        .addGap(37, 37, 37)))))
                        .addGap(1, 1, 1)))
                .addGap(105, 105, 105)
                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(komisioning_jumlah_tower_label)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAHSEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_komisioning_jumlah_tower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelAHSEM);
        jPanelAHSEM.setBounds(0, 0, 1230, 820);

        background_content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/bg_content1.jpg"))); // NOI18N
        getContentPane().add(background_content);
        background_content.setBounds(0, 0, 1230, 820);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_harga_aksesorisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_harga_aksesorisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_harga_aksesorisActionPerformed

    private void text_harga_insulatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_harga_insulatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_harga_insulatorActionPerformed

    private void insulator_quantity_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insulator_quantity_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insulator_quantity_combo_boxActionPerformed

    private void aksesoris_quantity_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aksesoris_quantity_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aksesoris_quantity_combo_boxActionPerformed

    private void stringing_quantity_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringing_quantity_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringing_quantity_combo_boxActionPerformed

    private void jText_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_hargaActionPerformed

    private void insulator_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insulator_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insulator_combo_boxActionPerformed

    private void stringing_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringing_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringing_combo_boxActionPerformed

    private void text_harga_stringingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_harga_stringingActionPerformed
    
    }//GEN-LAST:event_text_harga_stringingActionPerformed

    private void logo_plnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_plnMouseClicked
       new home().setVisible(true); 
       this.setVisible(false); 
    }//GEN-LAST:event_logo_plnMouseClicked

    private void stringing_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stringing_combo_boxItemStateChanged
         try {
            // TODO add your handling code here:
            String selectedValue = stringing_combo_box.getSelectedItem().toString();
         
            //tfHarga.setText(selectedValue);

            String sql = "select * from stringing where nama = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                String harga = rs.getString("harga");
                text_harga_stringing.setText(harga);
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                text_harga_stringing.setText(ut.getCurrencyFormat(currentcy));
//                
                stringing_quantity_combo_box.setSelectedIndex(1);
                 String sat = rs.getString("satuan");
                satuan_stringing.setText(sat);
               
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }   
    }//GEN-LAST:event_stringing_combo_boxItemStateChanged

    private void stringing_combo_boxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_stringing_combo_boxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stringing_combo_boxInputMethodTextChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:

            String sql = "select nama from stringing";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

//            while (rh.next()) {
//                String nama = rh.getString("nama");
//                //i++;
//                stringing_combo_box.addItem(nama);
//            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
        try {
            // TODO add your handling code here:

            String sql = "select nama from insulator";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

//            while (rh.next()) {
//                String nama = rh.getString("nama");
//                //i++;
//                stringing_combo_box.addItem(nama);
//            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
        try {
            // TODO add your handling code here:

            String sql = "select nama from aksesoris";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

//            while (rh.next()) {
//                String nama = rh.getString("nama");
//                //i++;
//                stringing_combo_box.addItem(nama);
//            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void insulator_combo_boxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_insulator_combo_boxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_insulator_combo_boxInputMethodTextChanged

    private void insulator_combo_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_insulator_combo_boxItemStateChanged
      try {
            // TODO add your handling code here:
            String selectedValue = insulator_combo_box.getSelectedItem().toString();
         
            //tfHarga.setText(selectedValue);

            String sql = "select * from insulator where nama = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                String harga = rs.getString("harga");
                text_harga_insulator.setText(harga);
                
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                text_harga_insulator.setText(ut.getCurrencyFormat(currentcy));
                
                insulator_quantity_combo_box.setSelectedIndex(1);
                String sat = rs.getString("satuan");
                satuan_insulator.setText(sat);
//                String sat = rs.getString("satuan");
//                SUpah.setText(sat);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }   
    }//GEN-LAST:event_insulator_combo_boxItemStateChanged

    private void nama_aksesoris_boxInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nama_aksesoris_boxInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_aksesoris_boxInputMethodTextChanged

    private void nama_aksesoris_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nama_aksesoris_boxItemStateChanged
         try {
            // TODO add your handling code here:
            String selectedValue = nama_aksesoris_box.getSelectedItem().toString();
//            String selectedSatuan = satuan_aksesoris_combo_box.getSelectedItem().toString();
            //tfHarga.setText(selectedValue);

            String sql = "select * from aksesoris where nama = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                String harga = rs.getString("harga");
                text_harga_aksesoris.setText(harga);
                
                 Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                text_harga_aksesoris.setText(ut.getCurrencyFormat(currentcy));
    
                aksesoris_quantity_combo_box.setSelectedIndex(1);
                
                String sat = rs.getString("satuan");
                satuan_aksesoris_TextField.setText(sat);
                
//                String sat = rs.getString("satuan");
//                SUpah.setText(sat);
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }   
    }//GEN-LAST:event_nama_aksesoris_boxItemStateChanged

    private void jText_komisioning_jumlah_towerCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jText_komisioning_jumlah_towerCaretUpdate
         String komisioning = jText_komisioning_jumlah_tower.getText();
        if (!komisioning.isEmpty()) {
         double persentaseKomisioning =  Double.parseDouble(komisioning);
            Double total = (persentaseKomisioning * 1999777);
            Utils ut = new Utils();
            String currentcy = String.valueOf(total);
            jText_harga.setText(ut.getCurrencyFormat(currentcy));
        System.out.println("ilham");
        }
    }//GEN-LAST:event_jText_komisioning_jumlah_towerCaretUpdate

    private void satuan_stringingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan_stringingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuan_stringingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AHSEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AHSEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AHSEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AHSEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AHSEM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aksesoris_label;
    private javax.swing.JLabel Stringing_label;
    private javax.swing.JComboBox<String> aksesoris_quantity_combo_box;
    private javax.swing.JLabel background_content;
    private javax.swing.JLabel harga_aksesoris_label;
    private javax.swing.JLabel harga_insulator_label;
    private javax.swing.JLabel harga_stringing_label;
    private javax.swing.JComboBox<String> insulator_combo_box;
    private javax.swing.JComboBox<String> insulator_quantity_combo_box;
    private javax.swing.JLabel insulator_tabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelAHSEM;
    private javax.swing.JTextField jText_harga;
    private javax.swing.JTextField jText_komisioning_jumlah_tower;
    private javax.swing.JLabel komisioning_jumlah_tower_label;
    private javax.swing.JLabel logo_pln;
    private javax.swing.JComboBox<String> nama_aksesoris_box;
    private javax.swing.JLabel quantity_aksesoris_label;
    private javax.swing.JLabel quantity_insulator_label;
    private javax.swing.JLabel quantity_stringing_label;
    private javax.swing.JTextField satuan_aksesoris_TextField;
    private javax.swing.JLabel satuan_aksesoris_label;
    private javax.swing.JTextField satuan_insulator;
    private javax.swing.JLabel satuan_insulator_label;
    private javax.swing.JTextField satuan_stringing;
    private javax.swing.JLabel satuan_stringing_label;
    private javax.swing.JComboBox<String> stringing_combo_box;
    private javax.swing.JComboBox<String> stringing_quantity_combo_box;
    private javax.swing.JTextField text_harga_aksesoris;
    private javax.swing.JTextField text_harga_insulator;
    private javax.swing.JTextField text_harga_stringing;
    private javax.swing.JLabel text_judul_AHS_pekerjaan_EM;
    // End of variables declaration//GEN-END:variables
}
