package cornet_desktop;

import cornet_desktop.database.DBConnection;
import cornet_desktop.presenter.HargaDasarPresenter;
import cornet_desktop.utils.Utils;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;


public class HargaDasar extends javax.swing.JFrame {
    private final HargaDasarPresenter hdp = new HargaDasarPresenter();
    private Double hargaTransport = 0.0;
    private final Utils utils = new Utils();
    public HargaDasar() {
        initComponents();
        hdp.loadDataUTK();
        hdp.loadDatanamaMEM();
        hdp.loadDatanamaMS();
        hdp.loadDatanamaSA();
        hdp.loadDatanamaTS();
        this.loadUTK();
        this.loadMEM();
        this.loadMS();
        this.loadSA();
        this.loadTS();
    }
    
    private void loadUTK(){
        List<String>
         utkList = hdp.getUTK();
        List<String> 
         utkHargaList = hdp.getHargaUTK();
        List<String> 
         utkRefList = hdp.getRefUTK();
        for(String data
                : utkList){
            DUpah.addItem(data);
        }
        for(String harga
                : utkHargaList){
            HUpah.setText(harga);
        }
        for(String ref
                : utkRefList){
            RUpah.setText(ref);
        }
    }

     private void loadMEM(){
        List<String> memList = hdp.getNamaMEM();
        for(String data
                : memList){
            DropME.addItem(data);
        }
    }
     
      private void loadMS(){
        List<String> msList = hdp.getNamaMS();
        for(String data
                : msList){
            DropMS.addItem(data);
        }
    }

      private void loadSA(){
        List<String> saList = hdp.getNamaSA();
        for(String data
                : saList){
            DropSewa.addItem(data);
        }
    }
      
      private void loadTS(){
        List<String> tsList = hdp.getTS();
        for(String data
                : tsList){
            DropITM.addItem(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        Uph = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Satuan = new javax.swing.JLabel();
        Refrensi = new javax.swing.JLabel();
        HUpah = new javax.swing.JTextField();
        HSipil = new javax.swing.JTextField();
        HEm = new javax.swing.JTextField();
        HSewa = new javax.swing.JTextField();
        SUpah = new javax.swing.JTextField();
        SSipil = new javax.swing.JTextField();
        SEm = new javax.swing.JTextField();
        SSewa = new javax.swing.JTextField();
        RUpah = new javax.swing.JTextField();
        RSipil = new javax.swing.JTextField();
        REm = new javax.swing.JTextField();
        RSewa = new javax.swing.JTextField();
        itm = new javax.swing.JLabel();
        KAwal = new javax.swing.JLabel();
        KTujuan = new javax.swing.JLabel();
        Asuran = new javax.swing.JLabel();
        TextAsuran = new javax.swing.JTextField();
        DUpah = new javax.swing.JComboBox();
        MSipil = new javax.swing.JLabel();
        DropMS = new javax.swing.JComboBox();
        DropME = new javax.swing.JComboBox();
        DropSewa = new javax.swing.JComboBox();
        ME = new javax.swing.JLabel();
        Sewa = new javax.swing.JLabel();
        HTotal = new javax.swing.JLabel();
        TextTotall = new javax.swing.JTextField();
        DropITM = new javax.swing.JComboBox();
        logo = new javax.swing.JLabel();
        jkt = new javax.swing.JLabel();
        ktujuan = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1230, 820));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1230, 820));

        Judul.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        Judul.setForeground(new java.awt.Color(240, 240, 240));
        Judul.setText("HARGA DASAR");

        Uph.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Uph.setForeground(new java.awt.Color(240, 240, 240));
        Uph.setText("Upah Tenaga Kerja");

        Harga.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Harga.setForeground(new java.awt.Color(240, 240, 240));
        Harga.setText("Harga");

        Satuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Satuan.setForeground(new java.awt.Color(240, 240, 240));
        Satuan.setText("Satuan");

        Refrensi.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Refrensi.setForeground(new java.awt.Color(240, 240, 240));
        Refrensi.setText("Refrensi");

        HUpah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HUpah.setMinimumSize(new java.awt.Dimension(200, 30));
        HUpah.setName(""); // NOI18N
        HUpah.setPreferredSize(new java.awt.Dimension(200, 30));
        HUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HUpahActionPerformed(evt);
            }
        });

        HSipil.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HSipil.setMinimumSize(new java.awt.Dimension(200, 30));
        HSipil.setPreferredSize(new java.awt.Dimension(200, 30));
        HSipil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSipilActionPerformed(evt);
            }
        });

        HEm.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HEm.setMinimumSize(new java.awt.Dimension(200, 30));
        HEm.setPreferredSize(new java.awt.Dimension(200, 30));
        HEm.setRequestFocusEnabled(false);
        HEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HEmActionPerformed(evt);
            }
        });

        HSewa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HSewa.setMinimumSize(new java.awt.Dimension(200, 30));
        HSewa.setPreferredSize(new java.awt.Dimension(200, 30));

        SUpah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        SUpah.setMinimumSize(new java.awt.Dimension(200, 30));
        SUpah.setPreferredSize(new java.awt.Dimension(200, 30));
        SUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUpahActionPerformed(evt);
            }
        });

        SSipil.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        SSipil.setMinimumSize(new java.awt.Dimension(200, 30));
        SSipil.setPreferredSize(new java.awt.Dimension(200, 30));

        SEm.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        SEm.setMinimumSize(new java.awt.Dimension(200, 30));
        SEm.setPreferredSize(new java.awt.Dimension(200, 30));
        SEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEmActionPerformed(evt);
            }
        });

        SSewa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        SSewa.setMinimumSize(new java.awt.Dimension(200, 30));
        SSewa.setPreferredSize(new java.awt.Dimension(200, 30));
        SSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSewaActionPerformed(evt);
            }
        });

        RUpah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        RUpah.setMinimumSize(new java.awt.Dimension(250, 30));
        RUpah.setName(""); // NOI18N
        RUpah.setPreferredSize(new java.awt.Dimension(250, 30));
        RUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUpahActionPerformed(evt);
            }
        });

        RSipil.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        RSipil.setMinimumSize(new java.awt.Dimension(250, 30));
        RSipil.setPreferredSize(new java.awt.Dimension(250, 30));
        RSipil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSipilActionPerformed(evt);
            }
        });

        REm.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        REm.setMinimumSize(new java.awt.Dimension(250, 30));
        REm.setPreferredSize(new java.awt.Dimension(250, 30));

        RSewa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        RSewa.setMinimumSize(new java.awt.Dimension(250, 30));
        RSewa.setPreferredSize(new java.awt.Dimension(250, 30));
        RSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSewaActionPerformed(evt);
            }
        });

        itm.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        itm.setForeground(new java.awt.Color(240, 240, 240));
        itm.setText("Inland Transport Material");

        KAwal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        KAwal.setForeground(new java.awt.Color(240, 240, 240));
        KAwal.setText("Kota Awal");

        KTujuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        KTujuan.setForeground(new java.awt.Color(240, 240, 240));
        KTujuan.setText("Kota Tujuan");

        Asuran.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Asuran.setForeground(new java.awt.Color(240, 240, 240));
        Asuran.setText("Asuransi");

        TextAsuran.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TextAsuran.setMinimumSize(new java.awt.Dimension(150, 30));
        TextAsuran.setPreferredSize(new java.awt.Dimension(200, 30));
        TextAsuran.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextAsuranCaretUpdate(evt);
            }
        });
        TextAsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAsuranActionPerformed(evt);
            }
        });

        DUpah.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DUpah.setMaximumRowCount(5);
        DUpah.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih -" }));
        DUpah.setMinimumSize(new java.awt.Dimension(300, 30));
        DUpah.setPreferredSize(new java.awt.Dimension(300, 30));
        DUpah.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DUpahItemStateChanged(evt);
            }
        });
        DUpah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DUpahInputMethodTextChanged(evt);
            }
        });
        DUpah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DUpahActionPerformed(evt);
            }
        });

        MSipil.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        MSipil.setForeground(new java.awt.Color(240, 240, 240));
        MSipil.setText("Material Sipil");

        DropMS.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DropMS.setMaximumRowCount(5);
        DropMS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih -" }));
        DropMS.setMinimumSize(new java.awt.Dimension(300, 30));
        DropMS.setPreferredSize(new java.awt.Dimension(300, 30));
        DropMS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DropMSItemStateChanged(evt);
            }
        });
        DropMS.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DropMSInputMethodTextChanged(evt);
            }
        });
        DropMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMSActionPerformed(evt);
            }
        });

        DropME.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DropME.setMaximumRowCount(5);
        DropME.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih -" }));
        DropME.setMinimumSize(new java.awt.Dimension(300, 30));
        DropME.setPreferredSize(new java.awt.Dimension(300, 30));
        DropME.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DropMEItemStateChanged(evt);
            }
        });
        DropME.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DropMEInputMethodTextChanged(evt);
            }
        });
        DropME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropMEActionPerformed(evt);
            }
        });

        DropSewa.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DropSewa.setMaximumRowCount(5);
        DropSewa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih -" }));
        DropSewa.setMinimumSize(new java.awt.Dimension(300, 30));
        DropSewa.setPreferredSize(new java.awt.Dimension(300, 30));
        DropSewa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DropSewaItemStateChanged(evt);
            }
        });
        DropSewa.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DropSewaInputMethodTextChanged(evt);
            }
        });
        DropSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropSewaActionPerformed(evt);
            }
        });

        ME.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ME.setForeground(new java.awt.Color(240, 240, 240));
        ME.setText("Material E/M");

        Sewa.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        Sewa.setForeground(new java.awt.Color(240, 240, 240));
        Sewa.setText("Sewa Alat");

        HTotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        HTotal.setForeground(new java.awt.Color(240, 240, 240));
        HTotal.setText("Harga");

        TextTotall.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TextTotall.setMinimumSize(new java.awt.Dimension(150, 30));
        TextTotall.setPreferredSize(new java.awt.Dimension(200, 30));
        TextTotall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTotallActionPerformed(evt);
            }
        });

        DropITM.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        DropITM.setMaximumRowCount(5);
        DropITM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- pilih -" }));
        DropITM.setMinimumSize(new java.awt.Dimension(300, 30));
        DropITM.setPreferredSize(new java.awt.Dimension(300, 30));
        DropITM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DropITMItemStateChanged(evt);
            }
        });
        DropITM.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DropITMInputMethodTextChanged(evt);
            }
        });
        DropITM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropITMActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo/logo PLN fix.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        jkt.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jkt.setForeground(new java.awt.Color(240, 240, 240));
        jkt.setText("Jakarta");

        ktujuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ktujuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-pilih-", "Lombok", "Sumbawa", "Flores", "Timor" }));
        ktujuan.setMinimumSize(new java.awt.Dimension(200, 30));
        ktujuan.setPreferredSize(new java.awt.Dimension(200, 30));
        ktujuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ktujuanItemStateChanged(evt);
            }
        });
        ktujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktujuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(338, 338, 338)
                        .addComponent(Judul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Uph)
                            .addComponent(DropSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DropMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ME)
                            .addComponent(MSipil)
                            .addComponent(Sewa)
                            .addComponent(DropME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DUpah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itm)
                            .addComponent(DropITM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Harga)
                                    .addComponent(HEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HUpah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Satuan)
                                    .addComponent(SUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Refrensi)
                                    .addComponent(RSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(REm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(KAwal)
                                    .addComponent(jkt))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ktujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KTujuan))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Asuran)
                                    .addComponent(TextAsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HTotal)
                                    .addComponent(TextTotall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addComponent(Judul))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(DropMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ME)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(DropME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(68, 68, 68)
                            .addComponent(Sewa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DropSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(HSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(HEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(374, 374, 374)
                                .addComponent(HSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(SSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(SEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(446, 446, 446)
                                .addComponent(SSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Satuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Refrensi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(404, 404, 404))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RSipil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(REm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Uph)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DUpah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(MSipil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(KTujuan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ktujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(KAwal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jkt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(itm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DropITM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(HTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextTotall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Asuran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextAsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1230, 820);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/bg_content1.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1100, 773));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1230, 820);

        jTextField17.setText("jTextField17");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(40, 440, 65, 20);

        jTextField18.setText("jTextField18");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(220, 430, 65, 20);

        jTextField19.setText("jTextField19");
        getContentPane().add(jTextField19);
        jTextField19.setBounds(390, 430, 65, 20);

        jTextField20.setText("jTextField20");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(520, 430, 65, 20);

        jTextField21.setText("jTextField21");
        getContentPane().add(jTextField21);
        jTextField21.setBounds(630, 440, 65, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSewaActionPerformed

    private void DUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DUpahActionPerformed

    private void HUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HUpahActionPerformed

    private void SUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SUpahActionPerformed

    private void HSipilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSipilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HSipilActionPerformed

    private void HEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HEmActionPerformed

    private void SEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEmActionPerformed

    private void SSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSewaActionPerformed

    private void TextAsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAsuranActionPerformed

    private void RUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUpahActionPerformed

    private void TextTotallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTotallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTotallActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        new home().setVisible(true); 
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseClicked

    private void DUpahInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DUpahInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DUpahInputMethodTextChanged

    private void DUpahItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DUpahItemStateChanged
  try {
            // TODO add your handling code here:
            String selectedValue = DUpah.getSelectedItem().toString();
            //tfHarga.setText(selectedValue);

            String sql = "select * from upah_tenaga_kerja where nama = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                String harga = rs.getString("harga");
                HUpah.setText(harga);
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                HUpah.setText(ut.getCurrencyFormat(currentcy));              
                SUpah.setText("Hari");
                String ref = rs.getString("referensi");
                RUpah.setText(ref);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }    // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_DUpahItemStateChanged

    private void DropMSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DropMSItemStateChanged
      try {
            // TODO add your handling code here:
            String selectedValue = DropMS.getSelectedItem().toString();
            //tfHarga.setText(selectedValue);

            String sql = "select * from material_sipil where nama = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
               String harga = rs.getString("harga");
                HSipil.setText(harga);
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                HSipil.setText(ut.getCurrencyFormat(currentcy));
                String sat = rs.getString("satuan");
                SSipil.setText(sat);
                String ref = rs.getString("referensi");
                RSipil.setText(ref);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_DropMSItemStateChanged

    private void DropMSInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DropMSInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DropMSInputMethodTextChanged

    private void DropMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropMSActionPerformed

    private void DropMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropMEActionPerformed

    private void DropMEInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DropMEInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DropMEInputMethodTextChanged

    private void DropMEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DropMEItemStateChanged
         try {
            // TODO add your handling code here:
            String selectedValue = DropME.getSelectedItem().toString();
            //tfHarga.setText(selectedValue);

            String sql = "select * from material_em where material = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
               String harga = rs.getString("harga");
                HEm.setText(harga);
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                HEm.setText(ut.getCurrencyFormat(currentcy));
                String sat = rs.getString("satuan");
                SEm.setText(sat);
                String ref = rs.getString("referensi");
                REm.setText(ref);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }     // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_DropMEItemStateChanged

    private void DropSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropSewaActionPerformed

    private void DropSewaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DropSewaItemStateChanged
        try {
            // TODO add your handling code here:
            String selectedValue = DropSewa.getSelectedItem().toString();
            //tfHarga.setText(selectedValue);

            String sql = "select * from sewa_alat where material = '"+ selectedValue+"'";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                String harga = rs.getString("harga");
                HSewa.setText(harga);
//                String harga = rs.getString("harga");
                HSewa.setText(harga);
                Utils ut = new Utils();
                String currentcy = String.valueOf(harga);
                HSewa.setText(ut.getCurrencyFormat(currentcy));
                String sat = rs.getString("satuan");
                SSewa.setText(sat);
                String ref = rs.getString("referensi");
                RSewa.setText(ref);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }     // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_DropSewaItemStateChanged

    private void DropSewaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DropSewaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DropSewaInputMethodTextChanged

    private void DropITMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropITMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropITMActionPerformed

    private void DropITMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DropITMItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DropITMItemStateChanged

    private void DropITMInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DropITMInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DropITMInputMethodTextChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            String sql = "select nama from upah_tenaga_kerja";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

            while (rh.next()) {
                String nama = rh.getString("nama");
                //i++;
                DUpah.addItem(nama);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        try {
            // TODO add your handling code here:

            String sql = "select nama from material_sipil";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

            while (rh.next()) {
                String nama = rh.getString("nama");
                //i++;
                DropMS.addItem(nama);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        try {
            // TODO add your handling code here:

            String sql = "select material from material_em";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

            while (rh.next()) {
                String material = rh.getString("material");
                //i++;
                DropME.addItem(material);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        try {
            // TODO add your handling code here:

            String sql = "select material from sewa_alat";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

            while (rh.next()) {
                String material = rh.getString("material");
                //i++;
                DropSewa.addItem(material);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        try {
            // TODO add your handling code here:

            String sql = "select material from transport_material";
            //System.out.println(sql);
            Connection con = new DBConnection().getMyConnection();
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rh = stmt.executeQuery(sql);

            while (rh.next()) {
                String material = rh.getString("material");
                //i++;
                DropITM.addItem(material);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void RSipilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSipilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RSipilActionPerformed

    private void ktujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktujuanActionPerformed

    private void ktujuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ktujuanItemStateChanged
        String selected = ktujuan.getSelectedItem().toString();
        String material = DropITM.getSelectedItem().toString();
        switch (selected) {
            case "Lombok":
                hargaTransport = hdp.getHargaTransportasi(material, "transport_lombok");
            break;
            case "Sumbawa":
                hargaTransport = hdp.getHargaTransportasi(material, "transport_sumbawa");
            break; 
            case "Flores":
                hargaTransport = hdp.getHargaTransportasi(material, "transport_flores");
            break; 
            case "Timor":
                hargaTransport = hdp.getHargaTransportasi(material, "transport_timor");
            break; 
            
        }
    }//GEN-LAST:event_ktujuanItemStateChanged

    private void TextAsuranCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextAsuranCaretUpdate
        String asuransi = TextAsuran.getText();
        if (!asuransi.isEmpty()) {
        double persentaseAsuransi =  Double.parseDouble(asuransi);
            Double total = hargaTransport + (hargaTransport * persentaseAsuransi);
            Utils ut = new Utils();
            String currentcy = String.valueOf(total);
            TextTotall.setText(ut.getCurrencyFormat(currentcy));
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAsuranCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HargaDasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HargaDasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HargaDasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HargaDasar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HargaDasar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asuran;
    private javax.swing.JComboBox DUpah;
    private javax.swing.JComboBox DropITM;
    private javax.swing.JComboBox DropME;
    private javax.swing.JComboBox DropMS;
    private javax.swing.JComboBox DropSewa;
    private javax.swing.JTextField HEm;
    private javax.swing.JTextField HSewa;
    private javax.swing.JTextField HSipil;
    private javax.swing.JLabel HTotal;
    private javax.swing.JTextField HUpah;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel KAwal;
    private javax.swing.JLabel KTujuan;
    private javax.swing.JLabel ME;
    private javax.swing.JLabel MSipil;
    private javax.swing.JTextField REm;
    private javax.swing.JTextField RSewa;
    private javax.swing.JTextField RSipil;
    private javax.swing.JTextField RUpah;
    private javax.swing.JLabel Refrensi;
    private javax.swing.JTextField SEm;
    private javax.swing.JTextField SSewa;
    private javax.swing.JTextField SSipil;
    private javax.swing.JTextField SUpah;
    private javax.swing.JLabel Satuan;
    private javax.swing.JLabel Sewa;
    private javax.swing.JTextField TextAsuran;
    private javax.swing.JTextField TextTotall;
    private javax.swing.JLabel Uph;
    private javax.swing.JLabel itm;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JLabel jkt;
    private javax.swing.JComboBox<String> ktujuan;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
