package cornet_desktop;


public class home extends javax.swing.JFrame {
    
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        cost_estimation_icon = new javax.swing.JLabel();
        harga_dasar_icon = new javax.swing.JLabel();
        pekerjaan_sipil_icon = new javax.swing.JLabel();
        pekerjaan_em_icon = new javax.swing.JLabel();
        pln_logo = new javax.swing.JLabel();
        cost_estimation_text = new javax.swing.JLabel();
        harga_dasar_text = new javax.swing.JLabel();
        pekerjaan_sipil_text = new javax.swing.JLabel();
        pekerjaan_em_text = new javax.swing.JLabel();
        background_home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setPreferredSize(new java.awt.Dimension(1230, 820));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelHome.setBackground(new java.awt.Color(0, 24, 72));
        jPanelHome.setOpaque(false);
        jPanelHome.setPreferredSize(new java.awt.Dimension(1230, 820));

        cost_estimation_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/ic_cost_estimation23 (2).png"))); // NOI18N
        cost_estimation_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cost_estimation_iconMouseClicked(evt);
            }
        });

        harga_dasar_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/ic_harga_dasar4.png"))); // NOI18N
        harga_dasar_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                harga_dasar_iconMouseClicked(evt);
            }
        });

        pekerjaan_sipil_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/ic_pekerjaan_sipil2 (2).jpg"))); // NOI18N
        pekerjaan_sipil_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pekerjaan_sipil_iconMouseClicked(evt);
            }
        });

        pekerjaan_em_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/ic_pekerjaan_em3.png"))); // NOI18N
        pekerjaan_em_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pekerjaan_em_iconMouseClicked(evt);
            }
        });

        pln_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo/Logo_PLN (2).png"))); // NOI18N

        cost_estimation_text.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        cost_estimation_text.setText("COST ESTIMATION");

        harga_dasar_text.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        harga_dasar_text.setText("HARGA DASAR");

        pekerjaan_sipil_text.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        pekerjaan_sipil_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pekerjaan_sipil_text.setText("PEKERJAAN SIPIL");

        pekerjaan_em_text.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        pekerjaan_em_text.setText("PEKERJAAN E/M");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(harga_dasar_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(pekerjaan_sipil_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pekerjaan_em_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pln_logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(harga_dasar_text)
                .addGap(102, 102, 102)
                .addComponent(pekerjaan_sipil_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(pekerjaan_em_text)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(cost_estimation_text)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(cost_estimation_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(481, 481, 481))))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pln_logo)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(pekerjaan_em_icon)
                                .addGap(37, 37, 37))
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(cost_estimation_icon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cost_estimation_text)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(pekerjaan_sipil_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(harga_dasar_text)
                            .addComponent(pekerjaan_sipil_text)
                            .addComponent(pekerjaan_em_text)))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(harga_dasar_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelHome);
        jPanelHome.setBounds(0, 0, 1230, 820);

        background_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/bg_menu (2).jpg"))); // NOI18N
        background_home.setPreferredSize(new java.awt.Dimension(1230, 820));
        getContentPane().add(background_home);
        background_home.setBounds(0, 0, 1230, 820);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pekerjaan_em_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pekerjaan_em_iconMouseClicked
        AHSEM em = new AHSEM();
        em.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pekerjaan_em_iconMouseClicked

    private void harga_dasar_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_harga_dasar_iconMouseClicked
        HargaDasar hd = new HargaDasar();
        hd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_harga_dasar_iconMouseClicked

    private void pekerjaan_sipil_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pekerjaan_sipil_iconMouseClicked
        AHS ahs = new AHS();
        ahs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pekerjaan_sipil_iconMouseClicked

    private void cost_estimation_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cost_estimation_iconMouseClicked
        CostEstimation ce = new CostEstimation();
        ce.showLayout();
        this.setVisible(false);
    }//GEN-LAST:event_cost_estimation_iconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_home;
    private javax.swing.JLabel cost_estimation_icon;
    private javax.swing.JLabel cost_estimation_text;
    private javax.swing.JLabel harga_dasar_icon;
    private javax.swing.JLabel harga_dasar_text;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JLabel pekerjaan_em_icon;
    private javax.swing.JLabel pekerjaan_em_text;
    private javax.swing.JLabel pekerjaan_sipil_icon;
    private javax.swing.JLabel pekerjaan_sipil_text;
    private javax.swing.JLabel pln_logo;
    // End of variables declaration//GEN-END:variables
}
